// <auto-generated />
using System;
using DotacionWEBCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotacionWEBCore.Migrations.Database
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotacionWEBCore.Models.ListaAdministracion", b =>
                {
                    b.Property<int>("IdAdministracion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Administracion");

                    b.HasKey("IdAdministracion");

                    b.ToTable("DOTACION_Administracion");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaAñosServicio", b =>
                {
                    b.Property<int>("IdAnos_Servicio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anos_Servicio");

                    b.HasKey("IdAnos_Servicio");

                    b.ToTable("DOTACION_Anos_Servicio");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaBienios", b =>
                {
                    b.Property<int>("IdBienios")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bienios");

                    b.HasKey("IdBienios");

                    b.ToTable("DOTACION_Bienios");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaCargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.HasKey("IdCargo");

                    b.ToTable("DOTACION_Cargo");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaCategorias", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("DOTACION_Categoria");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaChofer", b =>
                {
                    b.Property<int>("IdFunciones_Chofer")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.Property<string>("Funciones_Chofer");

                    b.HasKey("IdFunciones_Chofer");

                    b.ToTable("DOTACION_Chofer");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaComunas", b =>
                {
                    b.Property<int>("ID_Comuna")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comuna");

                    b.Property<int>("ID_Comuna1");

                    b.Property<int>("ID_Servicio");

                    b.Property<string>("Servicio");

                    b.HasKey("ID_Comuna");

                    b.ToTable("DOTACION_Comunas");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaContratos", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdLey");

                    b.Property<string>("Ley");

                    b.Property<string>("Tipo_contrato");

                    b.HasKey("IdContrato");

                    b.ToTable("DOTACION_Contrato");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaDV", b =>
                {
                    b.Property<int>("IdDV")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DV");

                    b.HasKey("IdDV");

                    b.ToTable("DOTACION_DV");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaEspecialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Especialidad");

                    b.Property<int>("IdProfesion");

                    b.Property<string>("Profesion");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("DOTACION_Especialidad");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaEstablecimientos", b =>
                {
                    b.Property<int>("CodigoNuevo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Establecimiento");

                    b.Property<int>("ID_Comuna");

                    b.Property<int>("ID_Comuna1");

                    b.Property<int>("ID_Servicio");

                    b.HasKey("CodigoNuevo");

                    b.ToTable("DOTACION_Establecimientos");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaEstablecimientosMadres", b =>
                {
                    b.Property<int>("CodigoNuevoMadre")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstablecimientoMadre");

                    b.Property<int>("IdComuna");

                    b.Property<int>("IdComuna1");

                    b.Property<int>("IdServicio");

                    b.HasKey("CodigoNuevoMadre");

                    b.ToTable("DOTACION_EstablecimientosMadre");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaInscripcionSS", b =>
                {
                    b.Property<int>("IdInscripcionSS")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InscripcionSS");

                    b.HasKey("IdInscripcionSS");

                    b.ToTable("DOTACION_InscripcionSS");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaLey", b =>
                {
                    b.Property<int>("IdLey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ley");

                    b.HasKey("IdLey");

                    b.ToTable("DOTACION_Ley");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaModelo", b =>
                {
                    b.Property<int>("ID_Servicio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Administracion");

                    b.Property<string>("Anos_Servicio");

                    b.Property<string>("Bienios");

                    b.Property<string>("Cargo");

                    b.Property<string>("Categoria");

                    b.Property<int>("CodigoNuevo");

                    b.Property<int>("CodigoNuevoMadre");

                    b.Property<string>("Comuna");

                    b.Property<string>("DV");

                    b.Property<string>("Email");

                    b.Property<string>("Especialidad");

                    b.Property<string>("Establecimiento");

                    b.Property<string>("EstablecimientoMadre");

                    b.Property<string>("Fecha_Ingreso_Texto");

                    b.Property<string>("Fecha_Nacimiento_Texto");

                    b.Property<string>("Funciones_Chofer");

                    b.Property<int>("ID_Comuna");

                    b.Property<string>("ID_Establecimiento");

                    b.Property<int>("ID_EstablecimientoMadre");

                    b.Property<int>("IdCategoria");

                    b.Property<int>("IdContrato");

                    b.Property<int>("IdOrdenServicio");

                    b.Property<int>("IdProfesion");

                    b.Property<string>("IdServicioIdComuna");

                    b.Property<int>("IdTipoEstablecimiento");

                    b.Property<string>("InscripcionSS");

                    b.Property<string>("Ley");

                    b.Property<string>("Nacionalidad");

                    b.Property<string>("Nivel_Carrera");

                    b.Property<string>("Profesion");

                    b.Property<string>("Servicio");

                    b.Property<string>("Sexo");

                    b.Property<string>("Tipo_Establecimiento");

                    b.Property<string>("Tipo_Isapre");

                    b.Property<string>("Tipo_Prevision");

                    b.Property<string>("Tipo_contrato");

                    b.HasKey("ID_Servicio");

                    b.ToTable("DOTACION_Modelo");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaNacionalidad", b =>
                {
                    b.Property<int>("IdNacionalidad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nacionalidad");

                    b.HasKey("IdNacionalidad");

                    b.ToTable("DOTACION_Nacionalidad");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaNivelCarrera", b =>
                {
                    b.Property<int>("IdNivel_Carrera")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nivel_Carrera");

                    b.HasKey("IdNivel_Carrera");

                    b.ToTable("DOTACION_Nivel_Carrera");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaProfesiones", b =>
                {
                    b.Property<int>("IdProfesion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<int>("IdCategoria");

                    b.Property<string>("Profesion");

                    b.HasKey("IdProfesion");

                    b.ToTable("DOTACION_Profesion");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaRegistros", b =>
                {
                    b.Property<int>("ID_Registro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Activo");

                    b.Property<string>("Administracion");

                    b.Property<string>("Anos_Servicio");

                    b.Property<string>("Apellido_Materno");

                    b.Property<string>("Apellido_Paterno");

                    b.Property<string>("Bienios");

                    b.Property<string>("Cargo");

                    b.Property<string>("Categoria");

                    b.Property<string>("Comuna");

                    b.Property<string>("DV");

                    b.Property<string>("Especialidad");

                    b.Property<string>("Establecimiento");

                    b.Property<DateTime>("Fecha_Carga");

                    b.Property<string>("Fecha_Ingreso_Texto");

                    b.Property<string>("Fecha_Nacimiento_Texto");

                    b.Property<string>("Funciones_Chofer");

                    b.Property<string>("Haberes");

                    b.Property<string>("ID");

                    b.Property<int>("ID_Comuna");

                    b.Property<int>("ID_Establecimiento");

                    b.Property<int>("ID_Servicio");

                    b.Property<decimal>("Jornada");

                    b.Property<string>("Ley");

                    b.Property<string>("Nacionalidad");

                    b.Property<string>("Nivel_Carrera");

                    b.Property<string>("Nombre");

                    b.Property<string>("Profesion");

                    b.Property<int>("Revisado");

                    b.Property<string>("RevisadoTexto");

                    b.Property<string>("Rut");

                    b.Property<string>("SBase_Comunal");

                    b.Property<string>("Servicio");

                    b.Property<string>("Sexo");

                    b.Property<string>("Tipo_Isapre");

                    b.Property<string>("Tipo_Prevision");

                    b.Property<string>("Tipo_contrato");

                    b.Property<int>("Validado");

                    b.Property<string>("ValidadoTexto");

                    b.Property<string>("usuario");

                    b.HasKey("ID_Registro");

                    b.ToTable("DOTACION_Registros_resultados");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaRegistrosIR", b =>
                {
                    b.Property<int>("ID_Registro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Activo");

                    b.Property<string>("Administracion");

                    b.Property<string>("Anos_Servicio");

                    b.Property<string>("Apellido_Materno");

                    b.Property<string>("Apellido_Paterno");

                    b.Property<string>("Bienios");

                    b.Property<string>("Cargo");

                    b.Property<string>("Categoria");

                    b.Property<string>("Comuna");

                    b.Property<string>("DV");

                    b.Property<string>("Especialidad");

                    b.Property<string>("Establecimiento");

                    b.Property<DateTime>("Fecha_Carga");

                    b.Property<string>("Fecha_Ingreso_Texto");

                    b.Property<string>("Fecha_Nacimiento_Texto");

                    b.Property<string>("Funciones_Chofer");

                    b.Property<string>("Haberes");

                    b.Property<string>("ID");

                    b.Property<int>("ID_Comuna");

                    b.Property<int>("ID_Establecimiento");

                    b.Property<int>("ID_Servicio");

                    b.Property<decimal>("Jornada");

                    b.Property<string>("Ley");

                    b.Property<string>("Nacionalidad");

                    b.Property<string>("Nivel_Carrera");

                    b.Property<string>("Nombre");

                    b.Property<int>("PostulaRetiro");

                    b.Property<string>("PostulaRetiroTexto");

                    b.Property<string>("Profesion");

                    b.Property<int>("Revisado");

                    b.Property<string>("RevisadoTexto");

                    b.Property<string>("Rut");

                    b.Property<string>("SBase_Comunal");

                    b.Property<string>("Servicio");

                    b.Property<string>("Sexo");

                    b.Property<string>("Tipo_Isapre");

                    b.Property<string>("Tipo_Prevision");

                    b.Property<string>("Tipo_contrato");

                    b.Property<int>("Validado");

                    b.Property<string>("ValidadoTexto");

                    b.Property<string>("usuario");

                    b.HasKey("ID_Registro");

                    b.ToTable("DOTACION_Registros_resultados_IR");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaServicios", b =>
                {
                    b.Property<int>("IdOrdenServicio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_Servicio");

                    b.Property<string>("Servicio");

                    b.HasKey("IdOrdenServicio");

                    b.ToTable("DOTACION_Servicios");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaSexo", b =>
                {
                    b.Property<int>("IdSexo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sexo");

                    b.HasKey("IdSexo");

                    b.ToTable("DOTACION_Sexo");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaTipoEstablecimiento", b =>
                {
                    b.Property<int>("IdTipoEstablecimiento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo_Establecimiento");

                    b.HasKey("IdTipoEstablecimiento");

                    b.ToTable("DOTACION_Tipo_Establecimiento");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaTipoIsapre", b =>
                {
                    b.Property<int>("IdTipo_Isapre")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo_Isapre");

                    b.HasKey("IdTipo_Isapre");

                    b.ToTable("DOTACION_Tipo_Isapre");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaTipoPrevision", b =>
                {
                    b.Property<int>("IdTipo_Prevision")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo_Prevision");

                    b.HasKey("IdTipo_Prevision");

                    b.ToTable("DOTACION_Tipo_prevision");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.ListaUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_Comuna_U");

                    b.Property<int>("ID_Perfil");

                    b.Property<int>("IdServicio");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.Registros", b =>
                {
                    b.Property<int>("ID_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Registro")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido_Materno")
                        .HasColumnName("Apellido_Materno")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Apellido_Paterno")
                        .HasColumnName("Apellido_Paterno")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Categoria")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Dv")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Fecha_Carga");

                    b.Property<int>("ID_Comuna")
                        .HasColumnName("ID_Comuna");

                    b.Property<int>("ID_Establecimiento")
                        .HasColumnName("ID_Establecimiento");

                    b.Property<int>("ID_Servicio")
                        .HasColumnName("ID_Servicio");

                    b.Property<string>("Id_Cont")
                        .HasColumnName("Id_Cont");

                    b.Property<decimal>("Jornada")
                        .HasColumnType("numeric(2, 0)");

                    b.Property<string>("Ley");

                    b.Property<int?>("ListaAdministracionIdAdministracion");

                    b.Property<int?>("ListaAñosServicioIdAnos_Servicio");

                    b.Property<int?>("ListaBieniosIdBienios");

                    b.Property<int?>("ListaCargoIdCargo");

                    b.Property<int?>("ListaCategoriasIdCategoria");

                    b.Property<int?>("ListaChoferIdFunciones_Chofer");

                    b.Property<int?>("ListaContratosIdContrato");

                    b.Property<int?>("ListaDVIdDV");

                    b.Property<int?>("ListaEspecialidadIdEspecialidad");

                    b.Property<int?>("ListaEstablecimientosCodigoNuevo");

                    b.Property<int?>("ListaEstablecimientosMadresCodigoNuevoMadre");

                    b.Property<int?>("ListaInscripcionSSIdInscripcionSS");

                    b.Property<int?>("ListaLeyIdLey");

                    b.Property<int?>("ListaNacionalidadIdNacionalidad");

                    b.Property<int?>("ListaNivelCarreraIdNivel_Carrera");

                    b.Property<int?>("ListaProfesionesIdProfesion");

                    b.Property<int?>("ListaRegistrosID_Registro");

                    b.Property<int?>("ListaRegistrosIRID_Registro");

                    b.Property<int?>("ListaServiciosIdOrdenServicio");

                    b.Property<int?>("ListaSexoIdSexo");

                    b.Property<int?>("ListaTipoEstablecimientoIdTipoEstablecimiento");

                    b.Property<int?>("ListaTipoIsapreIdTipo_Isapre");

                    b.Property<int?>("ListaTipoPrevisionIdTipo_Prevision");

                    b.Property<int?>("ListaUsuariosId");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Profesion")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("RegistrosID_Registro");

                    b.Property<string>("Rut")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<string>("Sexo");

                    b.Property<string>("Tipo_Contrato");

                    b.Property<string>("usuario");

                    b.HasKey("ID_Registro");

                    b.HasIndex("ID_Comuna");

                    b.HasIndex("ID_Servicio");

                    b.HasIndex("ListaAdministracionIdAdministracion");

                    b.HasIndex("ListaAñosServicioIdAnos_Servicio");

                    b.HasIndex("ListaBieniosIdBienios");

                    b.HasIndex("ListaCargoIdCargo");

                    b.HasIndex("ListaCategoriasIdCategoria");

                    b.HasIndex("ListaChoferIdFunciones_Chofer");

                    b.HasIndex("ListaContratosIdContrato");

                    b.HasIndex("ListaDVIdDV");

                    b.HasIndex("ListaEspecialidadIdEspecialidad");

                    b.HasIndex("ListaEstablecimientosCodigoNuevo");

                    b.HasIndex("ListaEstablecimientosMadresCodigoNuevoMadre");

                    b.HasIndex("ListaInscripcionSSIdInscripcionSS");

                    b.HasIndex("ListaLeyIdLey");

                    b.HasIndex("ListaNacionalidadIdNacionalidad");

                    b.HasIndex("ListaNivelCarreraIdNivel_Carrera");

                    b.HasIndex("ListaProfesionesIdProfesion");

                    b.HasIndex("ListaRegistrosID_Registro");

                    b.HasIndex("ListaRegistrosIRID_Registro");

                    b.HasIndex("ListaServiciosIdOrdenServicio");

                    b.HasIndex("ListaSexoIdSexo");

                    b.HasIndex("ListaTipoEstablecimientoIdTipoEstablecimiento");

                    b.HasIndex("ListaTipoIsapreIdTipo_Isapre");

                    b.HasIndex("ListaTipoPrevisionIdTipo_Prevision");

                    b.HasIndex("ListaUsuariosId");

                    b.HasIndex("RegistrosID_Registro");

                    b.ToTable("DOTACION_Registros");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("DOTACION_Roles");
                });

            modelBuilder.Entity("DotacionWEBCore.Models.Registros", b =>
                {
                    b.HasOne("DotacionWEBCore.Models.ListaComunas")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ID_Comuna")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotacionWEBCore.Models.ListaModelo")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ID_Servicio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotacionWEBCore.Models.ListaAdministracion")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaAdministracionIdAdministracion");

                    b.HasOne("DotacionWEBCore.Models.ListaAñosServicio")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaAñosServicioIdAnos_Servicio");

                    b.HasOne("DotacionWEBCore.Models.ListaBienios")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaBieniosIdBienios");

                    b.HasOne("DotacionWEBCore.Models.ListaCargo")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaCargoIdCargo");

                    b.HasOne("DotacionWEBCore.Models.ListaCategorias")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaCategoriasIdCategoria");

                    b.HasOne("DotacionWEBCore.Models.ListaChofer")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaChoferIdFunciones_Chofer");

                    b.HasOne("DotacionWEBCore.Models.ListaContratos")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaContratosIdContrato");

                    b.HasOne("DotacionWEBCore.Models.ListaDV")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaDVIdDV");

                    b.HasOne("DotacionWEBCore.Models.ListaEspecialidad")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaEspecialidadIdEspecialidad");

                    b.HasOne("DotacionWEBCore.Models.ListaEstablecimientos")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaEstablecimientosCodigoNuevo");

                    b.HasOne("DotacionWEBCore.Models.ListaEstablecimientosMadres")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaEstablecimientosMadresCodigoNuevoMadre");

                    b.HasOne("DotacionWEBCore.Models.ListaInscripcionSS")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaInscripcionSSIdInscripcionSS");

                    b.HasOne("DotacionWEBCore.Models.ListaLey")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaLeyIdLey");

                    b.HasOne("DotacionWEBCore.Models.ListaNacionalidad")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaNacionalidadIdNacionalidad");

                    b.HasOne("DotacionWEBCore.Models.ListaNivelCarrera")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaNivelCarreraIdNivel_Carrera");

                    b.HasOne("DotacionWEBCore.Models.ListaProfesiones")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaProfesionesIdProfesion");

                    b.HasOne("DotacionWEBCore.Models.ListaRegistros")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaRegistrosID_Registro");

                    b.HasOne("DotacionWEBCore.Models.ListaRegistrosIR")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaRegistrosIRID_Registro");

                    b.HasOne("DotacionWEBCore.Models.ListaServicios")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaServiciosIdOrdenServicio");

                    b.HasOne("DotacionWEBCore.Models.ListaSexo")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaSexoIdSexo");

                    b.HasOne("DotacionWEBCore.Models.ListaTipoEstablecimiento")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaTipoEstablecimientoIdTipoEstablecimiento");

                    b.HasOne("DotacionWEBCore.Models.ListaTipoIsapre")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaTipoIsapreIdTipo_Isapre");

                    b.HasOne("DotacionWEBCore.Models.ListaTipoPrevision")
                        .WithMany("DOTACION_Registros")
                        .HasForeignKey("ListaTipoPrevisionIdTipo_Prevision");

                    b.HasOne("DotacionWEBCore.Models.ListaUsuarios")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("ListaUsuariosId");

                    b.HasOne("DotacionWEBCore.Models.Registros")
                        .WithMany("ListaModelo")
                        .HasForeignKey("RegistrosID_Registro");
                });
#pragma warning restore 612, 618
        }
    }
}
